### ISSUE TITLE
不能在Validate() error中定义错误信息吗

### ISSUE THREAD

**Issue by Xwudao** [lxzan/passport#9]
如题

**Comment by lxzan** [comment]
有自定义检查, 根据messageId去i18里面匹配

**Comment by lxzan** [comment]
内置的错误消息也可以被覆盖

```go
package main

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/xray-family/passport"
)

func main() {
	passport.SetLang(passport.Chinese)

	var err = passport.String("name", "").Required().Err()
	fmt.Printf("%v\n", err)

	_ = passport.GetBundle().AddMessages(passport.Chinese, &i18n.Message{
		ID:    "StringValue.Required",
		Other: "{{.Key}}不能为空哦",
	})
	err = passport.String("name", "").Required().Err()
	fmt.Printf("%v\n", err)
}

```

**Comment by Xwudao** [comment]
@lxzan 我的意思是这种：

```go
type Req struct {
	Name  string `json:"name"`
	Age   int    `json:"age"`
	Roles []int  `json:"roles"`
}

func (c *Req) Validate() error {
	return passport.Validate(
		passport.String("Name", c.Name).Required("必填").Alphabet("只能是字母"),
		passport.Ordered("Age", c.Age).Gte(18, "不能小于18岁"),
		passport.Slice("Roles", c.Roles).Required("必填"),
	)
}
```

不过你的第二种方式，好像也可以；只需要定义一次吧？

非常看好这个项目

**Comment by Xwudao** [comment]
![image](https://github.com/xray-family/passport/assets/31327868/5034df39-9bde-470a-8383-d6c7950d51f9)

尝试运行了一下，在哪里可以设置使用中文呢，默认是英文。我看`/assets`下面有中文翻译

**Comment by lxzan** [comment]
是的, 只需要加载一次

暂不支持在检查函数里面自定义错误消息, 这会让函数签名变复杂, 以后也许会加个WithContext的Option

**Comment by lxzan** [comment]
> ![image](https://private-user-images.githubusercontent.com/31327868/333518908-5034df39-9bde-470a-8383-d6c7950d51f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDA3ODUsIm5iZiI6MTcxNjU0MDQ4NSwicGF0aCI6Ii8zMTMyNzg2OC8zMzM1MTg5MDgtNTAzNGRmMzktOWJkZS00NzBhLTgzODMtZDZjNzk1MGQ1MWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MGUyMDA0NWQ5Zjc2NTU2YjM0MTZmZmEzNDUwZmVmYzgwZDFiOWM0YTNmNzUyYjljYWE0YTM3OTZkODllMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6ctThrm5FwZjavX9BLsqdvy5uqcjKPGawu_IV7m9Gc)
> 
> 尝试运行了一下，在哪里可以设置使用中文呢，默认是英文。我看`/assets`下面有中文翻译

看上面我发的代码

**Comment by Xwudao** [comment]
ok，了解了
